### ISSUE TITLE
New user questions

### ISSUE THREAD

**Issue by Tossrock** [Gentlymad-Studios/NewGraph#28]
Hey there! Just found your project via the NGP discord. Had a few questions about it before driving in 🙂

- Can we change the side of the node a port is attached to from horizontal to vertical?
- Are there sub graphs, or an intention to add them?
- Does the node editor this work at runtime? Being based on `GraphViewPlayer` it seems like it should, but you also seem to use assets for serialization, so maybe not?
- And... do you have a discord or other community for asking these kind of questions? Sorry if I'm asking in the wrong place!

**Comment by Doppelkeks** [comment]
Hey Tossrock,

_- Can we change the side of the node a port is attached to from horizontal to vertical?_
You can create custom inspectors for your nodes so in theory this should be possible but you would have to implement it yourself.

_- Are there sub graphs, or an intention to add them?_
Sub Graphs have already been requested [here](https://github.com/Gentlymad-Studios/NewGraph/issues/5), but currently I don't have any time to work on them as I'm in the process of stabilizing the current feature set. Since our studio does not have a use case where they are needed, they currently don't have a high priority for me.  I'm open to pull reqest though :)

_-Does the node editor this work at runtime? Being based on GraphViewPlayer it seems like it should, but you also seem to use assets for serialization, so maybe not?_
New Graph itself uses Unity's serialization system to work with MonoBehaviour's and ScriptableObject's. So yes, NewGraph is currently editor only but as you already said, since it's built on GraphViewPlayer you could use this more agnostic code base to write your own node graph for runtime. Here is a [link ](https://github.com/Gentlymad-Studios/GraphViewBase) to our modified GraphViewPlayer repository that is still editor/runtime agnostic but has a few bugfixes and additional methods.

_-And... do you have a discord or other community for asking these kind of questions? Sorry if I'm asking in the wrong place!_
Currently, there is no dedicated Discord, so asking here is perfectly fine. :)
