### ISSUE TITLE
No `Tools/GraphWindow` in the toolbar

### ISSUE THREAD

**Issue by likemango** [Gentlymad-Studios/NewGraph#31]
I have added `OdinSerializer` and `GraphViewBase`  in package manager, and clone the `NewGraph` repo in Asset Folder. It compiles fine  with no error or warning, but when I goto Wiki of Usage General Usage, I can't find  `Tools/GraphWindow` in my toolbar(I only see `Tools/Odin Serializer`).[General Usage 📒](https://github.com/Gentlymad-Studios/NewGraph/wiki/2.-Usage-%F0%9F%91%88#general-usage-)
I don't know why.

**Comment by Doppelkeks** [comment]
Thank you for highlighting this issue. Due to the effort to make this package more modular, you have to define your own entry point. To make this easier I created a small sample package you can import and the graph window will become accessible.

![image](https://github.com/Gentlymad-Studios/NewGraph/assets/530629/8c251bd0-a7f8-4507-bfef-29ee64a5dba0)
