### ISSUE TITLE
Low rendering efficiency by OnGUI()

### ISSUE THREAD

**Issue by likemango** [Gentlymad-Studios/NewGraph#32]
I see that NewGraph's UI element are still rendered by EditorWindow OnGUI() method，it means it has the same issue like IMGUI about low rendering efficiency(draw every frame)，Have you ever wondering how to improve that？

**Comment by Doppelkeks** [comment]
What part of it is still being drawn with the OnGUI method?

**Comment by Doppelkeks** [comment]
If you are hinting at the OnGUI call in the graph controller and the inspector, this method is not used to draw the graph, it is more of a utility method to get for example the graph overview list and popup menus to work. These are not drawing constantly but simply "when they are needed".

**Comment by Doppelkeks** [comment]
As I tried to explain this OnGUI method is only used for utility purposes like drawing popup overlays, that don't have a uielement equivalent, the rest and especially all the node and graph UI is using UIElements.

**Comment by Doppelkeks** [comment]
You can just open the uielements debugger and hover over the elements in the graph and you will see that it is all uitoolkit/uielements...

**Comment by likemango** [comment]
> You can just open the uielements debugger and hover over the elements in the graph and you will see that it is all uitoolkit/uielements...

Yes, it make sense. Thanks for your kindness reply. I have done a lot of surveys on workflow of building unity graph editor tools, but what I find is a mess. The key point is that GTF(graphTool foundations) and GraphView are expermental api, and IMGUI way is lack of effieciency and too old to use.

I'm so curious about how to render graph by scratch with UI Toolkits. I guess, [GraphViewBase](https://github.com/Gentlymad-Studios/GraphViewBase) have modify the source code of GraphView and make it as a dependency package, so by that, NewGraph can use it without any trouble whatever GraphView modified or abandoned.

Is that right?

**Comment by Doppelkeks** [comment]
Correct, GraphViewBase which was initially done by [Sahasrara](https://github.com/Sahasrara/GraphViewPlayer) is a minimized re-implementation of Unity's abandoned/deprecated GraphView. By using that instead of what ships with the Unity Engine we can avoid that tools break should Unity decide to remove this experimental GraphView API. We would still have to fix bugs with API changes to UIElements/UIToolkit but at least we have it in our hands and can modify the code directly and not be shut off.

As a side note: I talked with one of the engineers of GTF back in 2022 and they expressed their concerns that it will be a very long way to go until they will even start talking publicly about this API/package. Looks like this is currently pretty low on the bucket list of things.

So yeah, I was pretty much in the same boat as you. I was evaluating my options and since XNode turned out to be too slow for our Studios needs and without anything usable on the horizon we chose to go this way :)

**Comment by likemango** [comment]
> Correct, GraphViewBase which was initially done by [Sahasrara](https://github.com/Sahasrara/GraphViewPlayer) is a minimized re-implementation of Unity's abandoned/deprecated GraphView. By using that instead of what ships with the Unity Engine we can avoid that tools break should Unity decide to remove this experimental GraphView API. We would still have to fix bugs with API changes to UIElements/UIToolkit but at least we have it in our hands and can modify the code directly and not be shut off.
> 
> 
> 
> As a side note: I talked with one of the engineers of GTF back in 2022 and they expressed their concerns that it will be a very long way to go until they will even start talking publicly about this API/package. Looks like this is currently pretty low on the bucket list of things.
> 
> 
> 
> So yeah, I was pretty much in the same boat as you. I was evaluating my options and since XNode turned out to be too slow for our Studios needs and without anything usable on the horizon we chose to go this way :)
> 
> 
Great! Its definitely the best way to build Graph editor I ever thought. Thank you for sharing your visionary ideas.
By the way, do you have any discard channel that I can follow，sharing views or progress to the Graph Editor tools such as NewGraph ？
