### ISSUE TITLE
Error occur when drag a conncted node into a GroupCommentNode

### ISSUE THREAD

**Issue by likemango** [Gentlymad-Studios/NewGraph#33]
![error-newGraph](https://github.com/Gentlymad-Studios/NewGraph/assets/40531806/04abc785-f71a-4667-9943-a011e7e8e1e7)

**Comment by Doppelkeks** [comment]
Thanks for the bug report!
This has to do with some recent changes to GraphViewBase.

Since this is its own package you can request an older commit where this issue should not appear until we fixed it. Here is the link to the specific version (you can use it directly in the package manager): [https://github.com/Gentlymad-Studios/GraphViewBase.git#0ff5f7fb9154e4eebb75c0063fe134451d65d0ef](https://github.com/Gentlymad-Studios/GraphViewBase.git#0ff5f7fb9154e4eebb75c0063fe134451d65d0ef)

**Comment by Doppelkeks** [comment]
This has been fixed by [@leissler](https://github.com/leissler)
